### ISSUE TITLE
Problem with mconnect price rules when using PHP 8.1.13 

### ISSUE THREAD

**Issue by Coderdreams** [MalibuCommerceDev/mconnect-magento2#60]
When adding a price rule for a product, it seems that mconnect overrides the price of the product without setting the website_price key, that wasn't a problem in PHP 7.4 because it generated a warning and just returned an empty value in this code at vendor/magento/module-catalog/Block/Product/View.php:

        $tierPricesList = $priceInfo->getPrice('tier_price')->getTierPriceList();
        foreach ($tierPricesList as $tierPrice) {
            $tierPriceData = [
                'qty' => $tierPrice['price_qty'],
                'price' => $tierPrice['website_price'], // <<--- this line triggers error
            ];

But on PHP 8.1 it breaks execution because getting undefined keys are considered a critical error:

[2023-04-17T16:49:18.731541+00:00] report.CRITICAL: Exception: Warning: Undefined array key "website_price" in /app/x/vendor/magento/module-catalog/Block/Product/View.php on line 186 in /app/x/vendor/magento/framework/App/ErrorHandler.php:61

We were able to workaround this problem but it seems long term a fix in the extension would be the correct thing to do.

**Comment by giraclion** [comment]
@Coderdreams thank you for reporting the issue.

It was fixed in https://github.com/MalibuCommerceDev/mconnect-magento2/commit/8f1b700c85607d47f91b703724e6d2ffd29ce545
